### ISSUE TITLE
guild_view() does not launch the Guild View application

### ISSUE THREAD

**Issue by bbachman-data** [t-kalinowski/guildai-r#3]
I have installed the package on R-Studio (2022.07.1) with R 4.2.2 w/o any error message under Windows 10. guild_run runs smoothly with the example you provided. When I run guild_view() nothing happens.

I already did some checks: I specified a port for guild_view but it looks like that the port is not in use afterwards. I can however start the script "guild view" which opens a page in the web-browser but does not find any runs. I can also see the add-in in Rstudio. I also turned off the firewall completely w/o any effect.

Do I need to adapt some more settings?

**Comment by t-kalinowski** [comment]
Welcome! I think you're running into two issues here, one with GUILD_HOME, another with background processes on windows. 

For the GUILD_HOME issue, the quickest fix for you will be to set the env var GUILD_HOME to a path somewhere, e.g., "~/my-project/.guild" or "~/.guild". Then launched runs will be stored there, and `guild view` will look there when presenting runs. 

For the background-process-on-windows issue, it'll require a fix on the package end to use `processx::` instead of `system2()` to keep the "view" process alive. For now, please use the "guild view" launcher that works for you already, or call `export_guild_cli()` and call `guild view` from cmd.exe.

Note both these are temporary workarounds, until the required fixes are implemented.

**Comment by bbachman-data** [comment]
Thx. Thomas: Setting the GUILD_HOME variable as propsed made my day 👍
